const projects = {
    description: "We collect data across all projects developed by the Gloria Institute. In different ways we seek, constantly analyze predictions of behavior related to gender violence.",
    projects: [
        { title: "STEAM Power for Girls Project", images: [  ], description: "<b>STEAM Power for Girls</b> is an initiative of the US Embassy in Brazil in partnership with the Gloria Institute to train girls from public secondary schools in Brazil in future scientists. This initiative is focused on training in S.T.E.A.M subjects and it is a direct action for the empowerment of future leaders by means of education and skills development for the 21st century work." },
        { title: "Rede Convida - Tele Platform Service (2020 - ?)", images: [  ], description: "The Gloria Institute in partnership with the ‘Ciranda Sertaneja’ project and The medical Explorer project developed a platform for telehealth care for people in extreme situations of vulnerability ( socio-educational, transit houses, shelters ) .The beginning of service to the population was in June / 2020 and data are mining, anonymously, aiming to understand such contexts." },
        { title: "Game for new talents - 'The World of Gloria'", images: [ ], description: "After approval of the CNPq Universal Notice ( 2020 / 2021 ) , the Institute Gloria created a game for learning entrepreneurship, innovation and social responsibility for public schools ( 2nd grade ) in Brazil. In addition to developing an innovative business plan, players learn about sustainable development and digital inclusion to social projects in the world. All game development team members are students and volunteer professors from Brazilian Universities." },
        { title: "Social Actions", images: [ ], description: "<br>• In 2019 we served 1,150 children, youth and adults ( 450 needy children, 500 women from the Colméia penitentiary, 100 young people from the ViraVida Program ); <br> •	In partnership with the company Salon - Line, we distribute 100 care kits for the hair for black women. ; <br> •	In 2020 - Community Anniversary of 97 young people from the ViraVida Program (with delivery of gifts and snacks) ; <br> •	Distribution of 177 food baskets to vulnerable young people from the ViraVida program ( 97 in April and 80 in June ); <br> •	5 trousseaus for pregnant teenagers in a condition of total vulnerability; <br> •	We distributed 300 masks to the socio-educational system in Brasília; <br> •	With the help of the NGO ‘Miséria’, we ran quick tests for Covid 19 in the system male socio-educational in Brasília; <br> •	Conducting a course on sexual health for 97 inmates of the Educational Partner of the Federal District; <br> •	Delivery of food and blankets to 150 homeless people in Brasília ; <br> •	Women's Month 2021 Campaign: Delivery of Self-Care Kits to women undergoing drug treatment. Partnership between Gloria Institute and the Junior Company AD&M from University of Brasília" },
        { title: "Partnership in data collection for the UN World Report/Women (2020)", images: [ ], description: "With researchers in the area of law and medicine, the Gloria Institute participated in the survey of data in Brazil on violence against women and girls in a pandemic moment of COVID - 19 to the generation of the UN / Women's world report." },
        { title: "Structuring the Gloria's Digital Library (GDL) - 2020", images: [ ], description: "The Project ''Gloria's Digital Library information for all ” promotes the defense of women's rights, in favor of the prevention of female violence, autonomy and independence of women through access to digital information. In this sense, believes - that the development of these actions allow the search for equality of gender and universal access to information." },
        { title: "Videos from the Gloria project", images: [ ], description: "Creation of videos to institutionalize the Gloria Institute's actions acting in an educational way.: Portuguese/English Spanish 1 Spanish 2" },
        { title: "Financial Education for Girls of Public Schools", images: [ ], description: "Development of financial education methodology for Girls from Public Schools. This project is in the fundraising phase. The focus of action is train young people from public schools in the financial area. *It is planned to expand the work to semi-literate women low-income." },
        { title: "Signatory of the Global Compact - UN", images: [ ], description: "In 2020, Gloria Institute was selected as a signatory of the  <b> PactGlobal - UN. </b>" },
        { title: "TODAS ELAS – Assis Chateaubriand Foundation", images: [ ], description: "We were project partners TODAS ELAS – Assis Chateaubriand Foundation to accelerate business for 650 women low-income (up to R $ 500.00 / month) – 2020." },
        { title: "VOA Program - Ambev", images: [ ], description: "In 2021, we were approved in the VOA – Ambev Program . Program ofMentoring and support for the development of social innovations." },
        { title: "Entrepreneurship project for women who had an accident scalped. UNOPs - MPT", images: [ ], description: "2021 – We start a partnership with UNOPs / MPT to conduct research with women victims of scalping accidents in the north of Brazil. The project aims to initially serve 250 women to entrepreneurial training and socioeconomic mapping of these." },
        { title: "Microcredit program with women from Recife", images: [ ], description: "2021 - Project for research with the city of Recife for the performance of a microcredit program with women in condition of vulnerability." },
        { title: "Student Ambassador Gloria", images: [ ], description: "2021 - Training of high school girls in public schools for work with community projects aimed at combating violence in gender through educational content." },
        { title: "WEAmericas Network Ambassadors", images: [ ], description: "2021 - We signed an agreement with Ambassadors from WEAmericas Network (Americas and the Caribbean) for performance of projects developed by Gloria Institute these regions." },
        { title: "Gloria Security Map - Project looking for financing", images: [ ], description: "Self-declaring, secure and anonymous map for behavior pattern analysis of victims of gender violence. It will be possible collect information from 'victims or potential victims' and mine data to build narratives about the phenomenon." },
        { title: "Working Group - Women's Right", images: [ ], description: "2020 – We start a partnership between researchers in the field of law forming a working group to discuss gender and right in Brazil.This WG aims to identify, assess and discuss the relationship between violence, social inclusion and laws focused on gender issues." },
        { title: "CULTI/CNPq Research Group", images: [ ], description: "The ULTI Research Group develops studies and research in the themes: culture, organizational practices, innovation and internationalization, aiming to identify the relationship with social innovations. The group's objective is to promote the integration and cooperation of researchers and students for the development and dissemination of knowledge. The research group has already supported thesis development PhD, Master's theses, Initiation works Scientific, TCC, post - doctoral internships and extension projects. Have whether as partners the University of Brasilia, IESB, CornellUniversity, Université Aix Marseille III, Université Lili I, University of Lisbon." },
        { title: "eBook UMDI", images: [ ], description: "" },
    ],
    downloads: [
        { title: "UMDI - Um mundo de descobertas e invenções", img: "umdi.jpg", link: "http://tiny.cc/EbookUMDI" },
        { title: "Empreender = Mecanismos para cultivar competências (E=MC²)", img: "emc2.jpeg", link: "https://sites.google.com/view/ebook-emcc/início" },
    ]
}

export default projects